### ISSUE TITLE
Primordial leaves disable all block drops mod version [Fabric/Quilt] Eldritch End 0.2.31

### ISSUE THREAD

**Issue by ghost** [nvb-uy/Eldritch_End#14] opened 2024-02-11 18:57 UTC
Upon breaking Primordial leaves in survival mode with hand the error below is created. If you use ftb ultimine in addition ultimine mining fails breaks only one block and whole server is basicaly without item drops (even dropping from inventory the item gets deleted) it gets fixed only with server restart.

```
[19:42:02] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2846@45bb115b, suppressing error
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
        at net.minecraft.class_182.method_799(class_182.java:45) ~[server-intermediary.jar:?]
        at net.minecraft.class_182.test(class_182.java:20) ~[server-intermediary.jar:?]
        at java.util.function.Predicate.lambda$and$0(Predicate.java:69) ~[?:?]
        at net.minecraft.class_79.method_414(class_79.java:34) ~[server-intermediary.jar:?]
        at net.minecraft.class_85.expand(class_85.java:67) ~[server-intermediary.jar:?]
        at net.minecraft.class_64.method_16777(class_64.java:22) ~[server-intermediary.jar:?]
        at net.minecraft.class_69.expand(class_69.java:44) ~[server-intermediary.jar:?]
        at net.minecraft.class_55.method_345(class_55.java:58) ~[server-intermediary.jar:?]
        at net.minecraft.class_55.method_341(class_55.java:96) ~[server-intermediary.jar:?]
        at net.minecraft.class_52.method_328(class_52.java:86) ~[server-intermediary.jar:?]
        at net.minecraft.class_52.method_320(class_52.java:103) ~[server-intermediary.jar:?]
        at net.minecraft.class_52.method_319(class_52.java:116) ~[server-intermediary.jar:?]
        at net.minecraft.class_52.method_51878(class_52.java:111) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970.method_9560(class_4970.java:274) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26189(class_4970.java:1129) ~[server-intermediary.jar:?]
        at net.minecraft.class_2248.method_9609(class_2248.java:333) ~[server-intermediary.jar:?]
        at net.minecraft.class_2248.mixinextras$bridge$method_9609$104(class_2248.java) ~[server-intermediary.jar:?]
        at net.minecraft.class_2248.wrapOperation$fhh000$piercingpaxels$piercingPaxels$getStacks(class_2248.java:9184) ~[serverintermediary.jar:?]
        at net.minecraft.class_2248.method_9511(class_2248.java:352) ~[server-intermediary.jar:?]
        at net.minecraft.class_2248.method_9556(class_2248.java:431) ~[server-intermediary.jar:?]
        at net.minecraft.class_3225.method_14266(class_3225.java:275) ~[server-intermediary.jar:?]
        at net.minecraft.class_3225.method_21717(class_3225.java:228) ~[server-intermediary.jar:?]
        at net.minecraft.class_3225.method_14263(class_3225.java:203) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_12066(class_3244.java:1083) ~[server-intermediary.jar:?]
        at net.minecraft.class_2846.method_12361(class_2846.java:42) ~[server-intermediary.jar:?]
        at net.minecraft.class_2846.method_11054(class_2846.java:8) ~[server-intermediary.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by nvb-uy** [comment] 2024-02-16 01:48
Known issue, will be fixed on the next update which is coming out soon (0.3.0)

**Comment by nvb-uy** [comment] 2024-02-16 01:49
Duplicate of https://github.com/nvb-uy/Eldritch_End/issues/12

**Closed as not planned by nvb-uy** 2024-02-16 01:49 UTC
