### ISSUE TITLE
Statup Crash [Forge]

### ISSUE THREAD

**Issue by thedeerirty** [nvb-uy/Eldritch_End#6] opened 2023-12-12 02:00 UTC
[crash-2023-12-11_20.31.29-client.txt](https://github.com/nvb-uy/Eldritch_End/files/13642731/crash-2023-12-11_20.31.29-client.txt)
[crash-2023-12-11_20.33.42-client.txt](https://github.com/nvb-uy/Eldritch_End/files/13642732/crash-2023-12-11_20.33.42-client.txt)
[crash-2023-12-11_20.45.04-client.txt](https://github.com/nvb-uy/Eldritch_End/files/13642733/crash-2023-12-11_20.45.04-client.txt)
[crash-2023-12-11_20.48.50-client.txt](https://github.com/nvb-uy/Eldritch_End/files/13642734/crash-2023-12-11_20.48.50-client.txt)
[crash-2023-12-11_20.52.11-client.txt](https://github.com/nvb-uy/Eldritch_End/files/13642735/crash-2023-12-11_20.52.11-client.txt)

Having a strange crash with only Eldritch End (0.2.30) and its dependencies present. I thought it might be a repeat of #4 but my crash seems to be generating a report, and downgrading to connector beta 27 didn't fix my issue. Tried different versions of Eldritch End, connector, and forgified fabric API, but the crash continued to occur.

**Comment by nvb-uy** [comment] 2023-12-12 02:03
`Caused by: java.lang.RuntimeException: primordial_abyss.json - Failed to register config, it is likely that you added invalid entries in your config, or that the formatting isn't valid.`

Show me your Primordial Abyss config under config/eldritch_end/biomes/primordial_abyss

**Comment by thedeerirty** [comment] 2023-12-12 02:05
[primordial_abyss.json](https://github.com/nvb-uy/Eldritch_End/files/13642783/primordial_abyss.json)

Here - made no changes to it myself. All I've done is just try to boot the game after putting the mods in the folder.

**Comment by nvb-uy** [comment] 2023-12-12 02:11
I cannot reproduce this, could you test if running eldritch end on fabric with its dependencies works for you?

This is to file a report to Su5eD, because it is an interesting case and looks to be only happening to you

**Comment by thedeerirty** [comment] 2023-12-12 02:19
Sure, I'll get it set up here in a couple minutes and see whats what.

I'm not sure what it could be - is my version of Forge incorrect? Fairly sure I'm running 47.1.3.

**Comment by nvb-uy** [comment] 2023-12-12 02:20
Connector now supports newer versions, I tested myself on 47.2.6 and it worked fine, but please test in fabric so we can confirm it's not just an issue from your machine but rather something happening with connector ^^

**Comment by thedeerirty** [comment] 2023-12-12 02:24
Right, right. 

Fabric seemed to boot fine, no issues. Loaded a singleplayer world and everything was there.

**Comment by nvb-uy** [comment] 2023-12-12 02:27
Alright, I reported this to Su5eD so I'll update you through, at the moment you can try testing with forge 47.2.6 to see if it works.

Could you also send me your full modlist? It doesn't seem to display in the report

**Comment by thedeerirty** [comment] 2023-12-12 02:55
![image](https://github.com/nvb-uy/Eldritch_End/assets/58305182/0cdb701f-5f65-4385-820e-be3f838643a9)

connector's dependency displays as fabric-api - I assume there's a reason for that, but just in-case you weren't aware. i'll attempt to test 47.2.6 when I next get a chance.

**Comment by nvb-uy** [comment] 2023-12-12 03:09
oh you're missing connector extras, maybe that's why lol

**Comment by thedeerirty** [comment] 2023-12-12 03:48
Oh, does it require extras? If that's stated somewhere I must have missed it lol

It was listed as an optional dependency on Connector's page so I didn't give it much notice

**Comment by nvb-uy** [comment] 2023-12-12 05:40
Yeah in the EE forge file you can see its dependencies, connector extras is always marked as required

**Comment by thedeerirty** [comment] 2023-12-12 08:30
Ah, you can't see it on the new UI (I think). I downloaded without reverting to the legacy version:
![image](https://github.com/nvb-uy/Eldritch_End/assets/58305182/01260861-1ac6-4f1f-a7d2-cff00cb0661c)
and it wasn't listed under the general dependencies:
![image](https://github.com/nvb-uy/Eldritch_End/assets/58305182/f83e326d-0602-461f-bdd9-641c4cfe8360)

Real stupid change about that UI - makes it real hard to see what a mod needs to run.

**Comment by nvb-uy** [comment] 2023-12-13 11:27
curseforge moment lol

i'll assume this is resolved because you didn't post any further issue

**Closed as completed by nvb-uy** 2023-12-13 11:27 UTC
